vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\shahep
vti_timecreated:TR|26 Mar 2009 02:11:30 -0000
vti_timelastmodified:TR|13 Apr 2009 02:52:23 -0000
vti_filesize:IR|35396
vti_title:SR|预算管理系统--
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt/cx/ccs_gscxy_bmldcx_main.asp ccs_jt/cx/ccs_gscxy_main.asp
vti_nexttolasttimemodified:TR|08 Apr 2009 08:57:17 -0000
vti_cacheddtm:TX|13 Apr 2009 02:52:23 -0000
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_gscxy_main.asp S|images/bmcx_1.gif H|ccs_gscxy_index.asp S|images/fycx_1.gif H|ccs_gscxy_mxcx.asp S|images/flcx_cf.jpg S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif S|images/a.gif H|ccs_gscxy_bmldcx_index.asp H|ccs_gscxy_bmldcx_main.asp S|images/spacer.gif H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_index.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp H|ccs_gscxy_bmldcx_main_excel.asp
vti_cachedsvcrellinks:VX|FSUS|ccs_JT/cx/images/obj_hed1.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/obj_maintitle.gif FSUS|ccs_JT/cx/images/spacer.gif FHUS|ccs_jt/cx/ccs_gscxy_main.asp FSUS|ccs_JT/cx/images/bmcx_1.gif FHUS|ccs_jt/cx/ccs_gscxy_index.asp FSUS|ccs_JT/cx/images/fycx_1.gif FHUS|ccs_JT/cx/ccs_gscxy_mxcx.asp FSUS|ccs_JT/cx/images/flcx_cf.jpg FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/obj_hed2_left.jpg FSUS|ccs_JT/cx/images/obj_hed2_center2.jpg FSUS|ccs_JT/cx/images/obj_hed2_right.jpg FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/ba1_point.gif FSUS|ccs_JT/cx/images/lizztp1.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/lizztp5.gif FSUS|ccs_JT/cx/images/obj_hed2_right-.jpg FSUS|ccs_JT/cx/images/obj_left.jpg FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/a.gif FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_index.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FSUS|ccs_JT/cx/images/spacer.gif FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_index.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_main_excel.asp
vti_cachedtitle:SR|预算管理系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
