vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\shahep
vti_timecreated:TR|26 Mar 2009 02:11:33 -0000
vti_timelastmodified:TR|13 Apr 2009 03:30:43 -0000
vti_filesize:IR|37719
vti_title:SR|预算控制系统--
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt/km_add.asp ccs_jt/cx/ccs_gscxy_index_old.asp ccs_jt/km_copy1.asp ccs_jt/ytgl1.asp ccs_jt/ytgl.asp ccs_jt/cx/ccs_gscxy_mxcx_zycx.asp ccs_jt/km_add1.asp ccs_jt/ys_init1.asp ccs_jt/yt_ch1.asp ccs_jt/yt_ts1.asp ccs_jt/cx/ccs_gscxy_mxcx_tscx_lb.asp ccs_jt/cx/ccs_gscxy_bmldcx_index.asp ccs_jt/cx/ccs_gscxy_mxcx_ytcx_lb.asp ccs_jt/query1_bk.asp ccs_jt/ys_init.asp ccs_jt/yt_ch.asp ccs_jt/km_copy.asp ccs_jt/query2.asp ccs_jt/ysgl.asp ccs_jt/yt_cx.asp ccs_jt/cx/ccs_gscxy_mxcx.asp ccs_jt/cx/ccs_gscxy_mxcx_czcx.asp ccs_jt/cx/ccs_gscxy_mxcx_czcx_lb.asp ccs_jt/cx/ccs_gscxy_mxcx_kmcx_lb.asp ccs_jt/cx/ccs_gscxy_mxcx_tscx.asp ccs_jt/cwmain_cx.asp ccs_jt/cwmain.asp ccs_jt/yt_ts.asp ccs_jt/ytgl1(old).asp ccs_jt/cx/ccs_gscxy_mxcx_kmcx.asp ccs_jt/query1.asp ccs_jt/cx/ccs_gscxy_bmldcx_main.asp ccs_jt/cx/ccs_gscxy_main.asp ccs_jt/cx/ccs_gscxy_mxcx_kmcx_lb_dc.asp ccs_jt/query2_cncx.asp ccs_jt/ccs_gkbm_add.asp ccs_jt/kmgl.asp ccs_jt/cx/ccs_gscxy_mxcx_ytcx.asp ccs_jt/cx/ccs_gscxy_mxcx_zycx_lb.asp ccs_jt/query1_cncx.asp ccs_jt/yt_cx1.asp ccs_jt/cx/ccs_gscxy_index.asp
vti_nexttolasttimemodified:TR|13 Apr 2009 02:54:42 -0000
vti_cacheddtm:TX|13 Apr 2009 02:54:42 -0000
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_gscxy_main.asp S|images/bmcx_1.gif H|ccs_gscxy_index.asp S|images/fycx_1.gif H|ccs_gscxy_mxcx.asp S|images/flcx_cf.jpg S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif H|javascript:void(null) H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp S|images/spacer.gif H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_bmldcx_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp
vti_cachedsvcrellinks:VX|FSUS|ccs_JT/cx/images/obj_hed1.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/obj_maintitle.gif FSUS|ccs_JT/cx/images/spacer.gif FHUS|ccs_JT/cx/ccs_gscxy_main.asp FSUS|ccs_JT/cx/images/bmcx_1.gif FHUS|ccs_JT/cx/ccs_gscxy_index.asp FSUS|ccs_JT/cx/images/fycx_1.gif FHUS|ccs_JT/cx/ccs_gscxy_mxcx.asp FSUS|ccs_JT/cx/images/flcx_cf.jpg FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/obj_hed2_left.jpg FSUS|ccs_JT/cx/images/obj_hed2_center2.jpg FSUS|ccs_JT/cx/images/obj_hed2_right.jpg FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/ba1_point.gif FSUS|ccs_JT/cx/images/lizztp1.gif FSUS|ccs_JT/cx/images/spacer.gif FSUS|ccs_JT/cx/images/lizztp5.gif FSUS|ccs_JT/cx/images/obj_hed2_right-.jpg FSUS|ccs_JT/cx/images/obj_left.jpg FSUS|ccs_JT/cx/images/spacer.gif SHUS|javascript:void(null) FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FSUS|ccs_JT/cx/images/spacer.gif FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_bmldcx_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp FHUS|ccs_JT/cx/ccs_gscxy_index_excel.asp
vti_cachedtitle:SR|预算控制系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
