vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 Apr 2007 00:41:23 -0000
vti_extenderversion:SR|4.0.2.7802
vti_cacheddtm:TX|06 Apr 2007 00:41:23 -0000
vti_filesize:IR|27008
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_gscxy_main.asp S|images/bmcx_1.gif H|ccs_gscxy_index.asp S|images/fycx_1.gif S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif S|images/a.gif H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp S|images/spacer.gif A|ccs_gscxy_index_Kmcode_cx.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_bmldcx_main.asp H|ccs_gscxy_index.asp
vti_cachedsvcrellinks:VX|FSUS|ccs_gz_lastyear/images/obj_hed1.gif FSUS|ccs_gz_lastyear/images/spacer.gif FSUS|ccs_gz_lastyear/images/obj_maintitle.gif FSUS|ccs_gz_lastyear/images/spacer.gif FHUS|ccs_gz_lastyear/ccs_gscxy_main.asp FSUS|ccs_gz_lastyear/images/bmcx_1.gif FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FSUS|ccs_gz_lastyear/images/fycx_1.gif FSUS|ccs_gz_lastyear/images/spacer.gif FSUS|ccs_gz_lastyear/images/obj_hed2_left.jpg FSUS|ccs_gz_lastyear/images/obj_hed2_center2.jpg FSUS|ccs_gz_lastyear/images/obj_hed2_right.jpg FSUS|ccs_gz_lastyear/images/spacer.gif FSUS|ccs_gz_lastyear/images/spacer.gif FSUS|ccs_gz_lastyear/images/spacer.gif FSUS|ccs_gz_lastyear/images/ba1_point.gif FSUS|ccs_gz_lastyear/images/lizztp1.gif FSUS|ccs_gz_lastyear/images/spacer.gif FSUS|ccs_gz_lastyear/images/lizztp5.gif FSUS|ccs_gz_lastyear/images/obj_hed2_right-.jpg FSUS|ccs_gz_lastyear/images/obj_left.jpg FSUS|ccs_gz_lastyear/images/spacer.gif FSUS|ccs_gz_lastyear/images/a.gif FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FSUS|ccs_gz_lastyear/images/spacer.gif FAUS|ccs_gz_lastyear/ccs_gscxy_index_Kmcode_cx.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp FHUS|ccs_gz_lastyear/ccs_bmldcx_main.asp FHUS|ccs_gz_lastyear/ccs_gscxy_index.asp
vti_cachedtitle:SR|深圳公司预算管理系统--
vti_title:SR|深圳公司预算管理系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_backlinkinfo:VX|
