vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\shahep
vti_timecreated:TR|16 Apr 2007 01:25:31 -0000
vti_timelastmodified:TR|09 Aug 2007 08:37:49 -0000
vti_filesize:IR|28864
vti_title:SR|深圳公司预算管理系统--
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs/cx/ccs_gscxy_index.asp ccs/cx/ccs_gscxy_mxcx_kmcx_lb.asp ccs/cx/ccs_gscxy_mxcx_kmcx_lb_dc.asp ccs/yt_ch1.asp ccs_gz_lastyear/ytgl1.asp ccs/yt_cx.asp ccs_gz_lastyear/cwmain.asp ccs_gz_lastyear/yt_ts1.asp ccs/ysgl.asp ccs_gz_lastyear/query1.asp ccs_gz_lastyear/ytgl1(old).asp ccs_gz_lastyear/yt_ch.asp ccs/cx/ccs_gscxy_mxcx_tscx.asp ccs_gz_lastyear/km_add.asp ccs_gz_lastyear/ys_init.asp ccs_gz_lastyear/ytgl.asp ccs/kmgl.asp ccs/km_add1.asp ccs_gz_lastyear/km_copy.asp ccs_gz_lastyear/yt_ts.asp ccs/cx/ccs_gscxy_bmldcx_index.asp ccs/cx/ccs_gscxy_bmldcx_main.asp ccs/cx/ccs_gscxy_main.asp ccs/cx/ccs_gscxy_mxcx_ytcx_lb.asp ccs/ytgl.asp ccs/yt_cx1.asp ccs/km_copy1.asp ccs_gz_lastyear/ys_init1.asp ccs/cx/ccs_gscxy_index_old.asp ccs/cx/ccs_gscxy_mxcx_ytcx.asp ccs/cx/ccs_gscxy_mxcx_zycx.asp ccs/cx/ccs_gscxy_mxcx_zycx_lb.asp ccs/yt_ts1.asp ccs/ys_init1.asp ccs/ys_init.asp ccs/cwmain.asp ccs/cx/ccs_gscxy_mxcx_czcx_lb.asp ccs/yt_ch.asp ccs/query1.asp ccs/km_copy.asp ccs/km_add.asp ccs_gz_lastyear/km_copy1.asp ccs_gz_lastyear/ysgl.asp ccs_gz_lastyear/kmgl.asp ccs_gz_lastyear/km_add1.asp ccs_gz_lastyear/yt_ch1.asp ccs/cx/ccs_gscxy_mxcx_czcx.asp ccs/ytgl1.asp ccs_gz_lastyear/yt_cx.asp ccs/cx/ccs_gscxy_mxcx.asp ccs/cx/ccs_gscxy_mxcx_kmcx.asp ccs/cx/ccs_gscxy_mxcx_tscx_lb.asp ccs/yt_ts.asp ccs/ytgl1(old).asp ccs_gz_lastyear/yt_cx1.asp
vti_cacheddtm:TX|09 Aug 2007 08:37:49 -0000
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_gscxy_main.asp S|images/bmcx_1.gif H|ccs_gscxy_index.asp S|images/fycx_1.gif H|ccs_gscxy_mxcx.asp S|images/flcx_cf.jpg S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif H|javascript:void(null) H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp S|images/spacer.gif H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_bmldcx_index.asp H|ccs_gscxy_index.asp
vti_cachedsvcrellinks:VX|FSUS|ccs_gz/cx/images/obj_hed1.gif FSUS|ccs_gz/cx/images/spacer.gif FSUS|ccs_gz/cx/images/obj_maintitle.gif FSUS|ccs_gz/cx/images/spacer.gif FHUS|ccs_gz/cx/ccs_gscxy_main.asp FSUS|ccs_gz/cx/images/bmcx_1.gif FHUS|ccs_gz/cx/ccs_gscxy_index.asp FSUS|ccs_gz/cx/images/fycx_1.gif FHUS|ccs_gz/cx/ccs_gscxy_mxcx.asp FSUS|ccs_gz/cx/images/flcx_cf.jpg FSUS|ccs_gz/cx/images/spacer.gif FSUS|ccs_gz/cx/images/obj_hed2_left.jpg FSUS|ccs_gz/cx/images/obj_hed2_center2.jpg FSUS|ccs_gz/cx/images/obj_hed2_right.jpg FSUS|ccs_gz/cx/images/spacer.gif FSUS|ccs_gz/cx/images/spacer.gif FSUS|ccs_gz/cx/images/spacer.gif FSUS|ccs_gz/cx/images/ba1_point.gif FSUS|ccs_gz/cx/images/lizztp1.gif FSUS|ccs_gz/cx/images/spacer.gif FSUS|ccs_gz/cx/images/lizztp5.gif FSUS|ccs_gz/cx/images/obj_hed2_right-.jpg FSUS|ccs_gz/cx/images/obj_left.jpg FSUS|ccs_gz/cx/images/spacer.gif SHUS|javascript:void(null) FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FSUS|ccs_gz/cx/images/spacer.gif FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp FHUS|ccs_gz/cx/ccs_gscxy_bmldcx_index.asp FHUS|ccs_gz/cx/ccs_gscxy_index.asp
vti_cachedtitle:SR|深圳公司预算管理系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
