vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\sharpbird
vti_timecreated:TR|31 Mar 2009 01:57:14 -0000
vti_timelastmodified:TR|31 Mar 2009 01:57:14 -0000
vti_cacheddtm:TX|31 Mar 2009 01:57:14 -0000
vti_filesize:IR|23885
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_gscxy_main.asp S|images/bmcx_1.gif H|ccs_gscxy_index.asp S|images/fycx_1.gif H|ccs_gscxy_mxcx.asp S|images/flcx_cf.jpg S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif S|images/a.gif H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_main.asp S|images/spacer.gif H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_main.asp H|ccs_gscxy_bmldcx_main.asp H|ccs_gscxy_main.asp
vti_cachedsvcrellinks:VX|NSUS|ccs_JT_lastyear/images/obj_hed1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_maintitle.gif NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp NSUS|ccs_JT_lastyear/images/bmcx_1.gif FHUS|ccs_JT_lastyear/ccs_gscxy_index.asp NSUS|ccs_JT_lastyear/images/fycx_1.gif FHUS|ccs_jt_lastyear/ccs_gscxy_mxcx.asp NSUS|ccs_JT_lastyear/images/flcx_cf.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_hed2_left.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_center2.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_right.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/ba1_point.gif NSUS|ccs_JT_lastyear/images/lizztp1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/lizztp5.gif NSUS|ccs_JT_lastyear/images/obj_hed2_right-.jpg NSUS|ccs_JT_lastyear/images/obj_left.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/a.gif FHUS|ccs_jt_lastyear/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp FHUS|ccs_jt_lastyear/ccs_gscxy_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_gscxy_main.asp
vti_cachedtitle:SR|深圳公司预算管理系统--全公司查询
vti_title:SR|深圳公司预算管理系统--全公司查询
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt_lastyear/ccs_gscxy_mxcx.asp ccs_jt_lastyear/ccs_gscxy_mxcx_czcx_lb.asp ccs_jt_lastyear/ccs_gscxy_index_old.asp ccs_jt_lastyear/ccs_gscxy_main.asp ccs_jt_lastyear/ccs_gscxy_mxcx_tscx_lb.asp ccs_jt_lastyear/ccs_gscxy_mxcx_ytcx.asp ccs_jt_lastyear/ccs_gscxy_mxcx_ytcx_lb.asp ccs_jt_lastyear/ccs_gscxy_bmldcx_index.asp ccs_jt_lastyear/ccs_gscxy_bmldcx_main.asp ccs_jt_lastyear/ccs_gscxy_index.asp ccs_jt_lastyear/ccs_gscxy_mxcx_czcx.asp ccs_jt_lastyear/ccs_gscxy_mxcx_tscx.asp ccs_jt_lastyear/ccs_gscxy_mxcx_zycx.asp ccs_jt_lastyear/ccs_gscxy_mxcx_zycx_lb.asp ccs_jt_lastyear/ccs_gscxy_mxcx_kmcx.asp ccs_jt_lastyear/ccs_gscxy_mxcx_kmcx_lb.asp
