vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\sharpbird
vti_timecreated:TR|31 Mar 2009 01:56:29 -0000
vti_timelastmodified:TR|08 Apr 2009 03:33:08 -0000
vti_filesize:IR|28286
vti_title:SR|公司预算管理系统--
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt_lastyear/ccs_bm_ytcx.asp ccs_jt_lastyear/ccs_bmgl_zytj.asp ccs_jt_lastyear/ccs_bm_ser1.asp ccs_jt_lastyear/ccs_bm_tscx.asp ccs_jt_lastyear/ccs_bmgl_zttj.asp ccs_jt_lastyear/ccs_bmgl_zytj_lb.asp ccs_jt_lastyear/ccs_bm_rzcx.asp ccs_jt_lastyear/ccs_bm_ser.asp ccs_jt_lastyear/ccs_bmgl_fltj.asp ccs_jt_lastyear/ccs_input_index.asp
vti_nexttolasttimemodified:TR|08 Apr 2009 03:29:46 -0000
vti_cacheddtm:TX|08 Apr 2009 03:29:46 -0000
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_bm_ser.asp S|images/ysglinfoin2.jpg H|ccs_input_index.asp S|images/bt_02_on.gif H|ccs_bmgl_zttj.asp S|images/gltj1.jpg H|ccs_bm_rzcx.asp S|images/bmrz1.jpg S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/bmysglsm2.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif H|javascript:void(null) H|ccs_bmgl_fltj.asp H|ccs_bmgl_zttj.asp S|images/spacer.gif H|ccs_bmgl_zytj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_zttj.asp H|ccs_bmgl_fltj.asp H|ccs_bmgl_zttj.asp
vti_cachedsvcrellinks:VX|NSUS|ccs_JT_lastyear/images/obj_hed1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_maintitle.gif NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_JT_lastyear/ccs_bm_ser.asp NSUS|ccs_JT_lastyear/images/ysglinfoin2.jpg FHUS|ccs_jt_lastyear/ccs_input_index.asp NSUS|ccs_JT_lastyear/images/bt_02_on.gif FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp NSUS|ccs_JT_lastyear/images/gltj1.jpg FHUS|ccs_JT_lastyear/ccs_bm_rzcx.asp NSUS|ccs_JT_lastyear/images/bmrz1.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_hed2_left.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_center2.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_right.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/ba1_point.gif NSUS|ccs_JT_lastyear/images/lizztp1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/bmysglsm2.gif NSUS|ccs_JT_lastyear/images/obj_hed2_right-.jpg NSUS|ccs_JT_lastyear/images/obj_left.jpg NSUS|ccs_JT_lastyear/images/spacer.gif SHUS|javascript:void(null) FHUS|ccs_JT_lastyear/ccs_bmgl_fltj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_jt_lastyear/ccs_bmgl_zytj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_fltj.asp FHUS|ccs_JT_lastyear/ccs_bmgl_zttj.asp
vti_cachedtitle:SR|公司预算管理系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
