vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\sharpbird
vti_timecreated:TR|31 Mar 2009 01:56:46 -0000
vti_timelastmodified:TR|08 Apr 2009 03:33:23 -0000
vti_filesize:IR|26543
vti_title:SR|深圳公司预算管理系统--
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt_lastyear/ccs_bmldcx_index.asp ccs_jt_lastyear/ccs_bmldcx_main.asp ccs_jt_lastyear/ccs_gscxy_index_old.asp ccs_jt_lastyear/ccs_gscxy_bmldcx_index.asp ccs_jt_lastyear/ccs_gsfzcx_main.asp ccs_jt_lastyear/ccs_gsldcx_index.asp ccs_jt_lastyear/ccs_gsfzcx_index.asp ccs_jt_lastyear/ccs_gsldcx_main.asp
vti_nexttolasttimemodified:TR|08 Apr 2009 03:30:46 -0000
vti_cacheddtm:TX|08 Apr 2009 03:30:31 -0000
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_gsldcx_main.asp S|images/bmcx_1.gif H|ccs_gsldcx_index.asp S|images/fycx_1.gif H|ccs_gsfzcx_main.asp S|images/bmcx_1.gif H|ccs_gsfzcx_index.asp S|images/fycx_1.gif S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif S|images/a.gif H|ccs_bmldcx_index.asp H|ccs_bmldcx_main.asp S|images/spacer.gif H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_main.asp H|ccs_bmldcx_index.asp H|ccs_bmldcx_main.asp
vti_cachedsvcrellinks:VX|NSUS|ccs_JT_lastyear/images/obj_hed1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_maintitle.gif NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_JT_lastyear/ccs_gsldcx_main.asp NSUS|ccs_JT_lastyear/images/bmcx_1.gif FHUS|ccs_JT_lastyear/ccs_gsldcx_index.asp NSUS|ccs_JT_lastyear/images/fycx_1.gif FHUS|ccs_JT_lastyear/ccs_gsfzcx_main.asp NSUS|ccs_JT_lastyear/images/bmcx_1.gif FHUS|ccs_JT_lastyear/ccs_gsfzcx_index.asp NSUS|ccs_JT_lastyear/images/fycx_1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_hed2_left.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_center2.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_right.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/ba1_point.gif NSUS|ccs_JT_lastyear/images/lizztp1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/lizztp5.gif NSUS|ccs_JT_lastyear/images/obj_hed2_right-.jpg NSUS|ccs_JT_lastyear/images/obj_left.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/a.gif FHUS|ccs_JT_lastyear/ccs_bmldcx_index.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_index.asp FHUS|ccs_JT_lastyear/ccs_bmldcx_main.asp
vti_cachedtitle:SR|深圳公司预算管理系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
