vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\sharpbird
vti_timecreated:TR|31 Mar 2009 02:00:19 -0000
vti_timelastmodified:TR|31 Mar 2009 02:00:19 -0000
vti_cacheddtm:TX|31 Mar 2009 02:00:19 -0000
vti_filesize:IR|40563
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_ysqk_index.asp S|images/bt_01_on.gif H|ccs_input_index.asp S|images/bt_02_on.gif H|ccs_yskh_index.asp S|images/bt_03_on.gif H|ccs_xtwf.asp S|images/bt_04_on.gif S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif S|images/a.gif H|ccs_ysqk_index.asp S|images/spacer.gif A|ccs_ysqk_cx.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp H|ccs_ysqk_mon.asp
vti_cachedsvcrellinks:VX|NSUS|ccs_JT_lastyear/images/obj_hed1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_maintitle.gif NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_JT_lastyear/ccs_ysqk_index.asp NSUS|ccs_JT_lastyear/images/bt_01_on.gif FHUS|ccs_jt_lastyear/ccs_input_index.asp NSUS|ccs_JT_lastyear/images/bt_02_on.gif FHUS|ccs_JT_lastyear/ccs_yskh_index.asp NSUS|ccs_JT_lastyear/images/bt_03_on.gif FHUS|ccs_JT_lastyear/ccs_xtwf.asp NSUS|ccs_JT_lastyear/images/bt_04_on.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_hed2_left.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_center2.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_right.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/ba1_point.gif NSUS|ccs_JT_lastyear/images/lizztp1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/lizztp5.gif NSUS|ccs_JT_lastyear/images/obj_hed2_right-.jpg NSUS|ccs_JT_lastyear/images/obj_left.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/a.gif FHUS|ccs_JT_lastyear/ccs_ysqk_index.asp NSUS|ccs_JT_lastyear/images/spacer.gif FAUS|ccs_JT_lastyear/ccs_ysqk_cx.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp FHUS|ccs_jt_lastyear/ccs_ysqk_mon.asp
vti_cachedtitle:SR|深圳公司预算管理系统
vti_title:SR|深圳公司预算管理系统
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" onLoad="MM_preloadimagess('images/bt_01_off.gif','images/bt_02_on.gif','images/bt_03_on.gif','images/bt_04_on.gif','images/bt_05_on.gif')">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt_lastyear/ccs_khxtwf_xg.asp ccs_jt_lastyear/ccs_yskh_cx_cl.asp ccs_jt_lastyear/ccs_ysqk_mon.asp ccs_jt_lastyear/ccs_xtwf.asp ccs_jt_lastyear/ccs_yskh_cx.asp ccs_jt_lastyear/ccs_yskh_index.asp ccs_jt_lastyear/ccs_ysqk_cx.asp ccs_jt_lastyear/ccs_lu_xg.asp ccs_jt_lastyear/ccs_yskh_del.asp ccs_jt_lastyear/ccs_ysqk_index.asp ccs_jt_lastyear/ccs_ser.asp ccs_jt_lastyear/ccs_xtwf_kh.asp ccs_jt_lastyear/ccs_xtwf_xg.asp
