vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\sharpbird
vti_timecreated:TR|31 Mar 2009 02:00:47 -0000
vti_timelastmodified:TR|31 Mar 2009 02:00:47 -0000
vti_cacheddtm:TX|31 Mar 2009 02:00:47 -0000
vti_filesize:IR|27653
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|kmgl.asp S|images/kemu.gif H|ysgl.asp S|images/yusuan.gif H|cw_gsldcx_index.asp S|images/gltj1.jpg H|cwmain.asp S|images/baoxiao.gif H|cw_gsldcx_index.asp S|images/gltj1.jpg H|ytgl.asp S|images/yuti.gif H|cw_gsldcx_index.asp S|images/gltj1.jpg S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif S|images/a.gif H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp S|images/spacer.gif H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_gsldcx_index.asp H|cw_bmldcx_main.asp H|cw_gsldcx_index.asp
vti_cachedsvcrellinks:VX|NSUS|ccs_JT_lastyear/images/obj_hed1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_maintitle.gif NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_jt_lastyear/kmgl.asp NSUS|ccs_JT_lastyear/images/kemu.gif FHUS|ccs_jt_lastyear/ysgl.asp NSUS|ccs_JT_lastyear/images/yusuan.gif FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp NSUS|ccs_JT_lastyear/images/gltj1.jpg FHUS|ccs_jt_lastyear/cwmain.asp NSUS|ccs_JT_lastyear/images/baoxiao.gif FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp NSUS|ccs_JT_lastyear/images/gltj1.jpg FHUS|ccs_jt_lastyear/ytgl.asp NSUS|ccs_JT_lastyear/images/yuti.gif FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp NSUS|ccs_JT_lastyear/images/gltj1.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/obj_hed2_left.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_center2.jpg NSUS|ccs_JT_lastyear/images/obj_hed2_right.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/ba1_point.gif NSUS|ccs_JT_lastyear/images/lizztp1.gif NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/lizztp5.gif NSUS|ccs_JT_lastyear/images/obj_hed2_right-.jpg NSUS|ccs_JT_lastyear/images/obj_left.jpg NSUS|ccs_JT_lastyear/images/spacer.gif NSUS|ccs_JT_lastyear/images/a.gif FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp NSUS|ccs_JT_lastyear/images/spacer.gif FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp FHUS|ccs_JT_lastyear/cw_bmldcx_main.asp FHUS|ccs_JT_lastyear/cw_gsldcx_index.asp
vti_cachedtitle:SR|深圳公司预算管理系统--
vti_title:SR|深圳公司预算管理系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt_lastyear/cw_bmldcx_index.asp ccs_jt_lastyear/cw_bmldcx_main.asp ccs_jt_lastyear/cw_gsldcx_index.asp ccs_jt_lastyear/cw_gsldcx_main.asp
