vti_encoding:SR|utf8-nl
vti_author:SR|SZX-KFB\\sharpbird
vti_modifiedby:SR|SZX-KFB\\sharpbird
vti_timecreated:TR|26 Mar 2009 02:01:43 -0000
vti_timelastmodified:TR|07 Apr 2009 08:43:27 -0000
vti_filesize:IR|37719
vti_title:SR|预算控制系统--
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_extenderversion:SR|4.0.2.7802
vti_backlinkinfo:VX|ccs_jt/ccs_gscxy_bmldcx_main.asp ccs_jt/ccs_gscxy_main.asp ccs_jt/ccs_gscxy_mxcx_ytcx.asp ccs_jt/ccs_gscxy_mxcx_zycx_lb.asp ccs_jt/ccs_gscxy_index_old.asp ccs_jt/ccs_gscxy_mxcx_czcx_lb.asp ccs_jt/ccs_gscxy_mxcx_kmcx_lb.asp ccs_jt/ccs_gscxy_mxcx_tscx.asp ccs_jt/ccs_gscxy_mxcx_zycx.asp ccs_jt/cnmain.asp ccs_jt/ccs_gscxy_mxcx.asp ccs_jt/ccs_gscxy_mxcx_czcx.asp ccs_jt/ccs_gscxy_mxcx_tscx_lb.asp ccs_jt/ccs_gscxy_bmldcx_index.asp ccs_jt/ccs_gscxy_index.asp ccs_jt/ccs_gscxy_mxcx_kmcx.asp ccs_jt/ccs_gscxy_mxcx_kmcx_lb_dc.asp ccs_jt/ccs_gscxy_mxcx_ytcx_lb.asp
vti_nexttolasttimemodified:TR|07 Apr 2009 08:13:07 -0000
vti_cacheddtm:TX|07 Apr 2009 08:13:07 -0000
vti_cachedlinkinfo:VX|S|images/obj_hed1.gif S|images/spacer.gif S|images/obj_maintitle.gif S|images/spacer.gif H|ccs_gscxy_main.asp S|images/bmcx_1.gif H|ccs_gscxy_index.asp S|images/fycx_1.gif H|ccs_gscxy_mxcx.asp S|images/flcx_cf.jpg S|images/spacer.gif S|images/obj_hed2_left.jpg S|images/obj_hed2_center2.jpg S|images/obj_hed2_right.jpg S|images/spacer.gif S|images/spacer.gif S|images/spacer.gif S|images/ba1_point.gif S|images/lizztp1.gif S|images/spacer.gif S|images/lizztp5.gif S|images/obj_hed2_right-.jpg S|images/obj_left.jpg S|images/spacer.gif H|javascript:void(null) H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp S|images/spacer.gif H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_bmldcx_index.asp H|ccs_gscxy_index.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp H|ccs_gscxy_index_excel.asp
vti_cachedsvcrellinks:VX|FSUS|ccs_JT/images/obj_hed1.gif FSUS|ccs_JT/images/spacer.gif FSUS|ccs_JT/images/obj_maintitle.gif FSUS|ccs_JT/images/spacer.gif FHUS|ccs_jt/ccs_gscxy_main.asp FSUS|ccs_JT/images/bmcx_1.gif FHUS|ccs_JT/ccs_gscxy_index.asp FSUS|ccs_JT/images/fycx_1.gif FHUS|ccs_jt/ccs_gscxy_mxcx.asp FSUS|ccs_JT/images/flcx_cf.jpg FSUS|ccs_JT/images/spacer.gif FSUS|ccs_JT/images/obj_hed2_left.jpg FSUS|ccs_JT/images/obj_hed2_center2.jpg FSUS|ccs_JT/images/obj_hed2_right.jpg FSUS|ccs_JT/images/spacer.gif FSUS|ccs_JT/images/spacer.gif FSUS|ccs_JT/images/spacer.gif FSUS|ccs_JT/images/ba1_point.gif FSUS|ccs_JT/images/lizztp1.gif FSUS|ccs_JT/images/spacer.gif FSUS|ccs_JT/images/lizztp5.gif FSUS|ccs_JT/images/obj_hed2_right-.jpg FSUS|ccs_JT/images/obj_left.jpg FSUS|ccs_JT/images/spacer.gif SHUS|javascript:void(null) FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FSUS|ccs_JT/images/spacer.gif FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_JT/ccs_gscxy_bmldcx_index.asp FHUS|ccs_JT/ccs_gscxy_index.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp FHUS|ccs_jt/ccs_gscxy_index_excel.asp
vti_cachedtitle:SR|预算控制系统--
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" text="#000000" link="#3333FF" >
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
